### ISSUE TITLE
[Bug]：更新了动态，截图失败

### ISSUE THREAD

**Issue by AtaraxiaEta** [djkcyl/BBot-Graia#59]
### 需要由您确认的事项

- [X] 我已阅读了项目的 Wiki，并且成功安装了所需的所有依赖。
- [X] 我已经使用 GitHub 的 Issue 搜索功能，并且确认我的问题并未被提出或解决。
- [X] 我已经确认我的问题不是上游错误。
- [ ] 是否为 Release 的一键启动包。

### 系统

Linux

### IDC

腾讯云

### Python 版本

python:3.10.11-slim

### BBot 版本

V1.3.2 & 1.2.4b3

### Mirai 版本号

v2.14

### Mirai API HTTP 版本号

v2.9.1

### 问题简述

我之前使用的是1.2.4b3版本，大概从5.23开始出现截图失败的情况并且无限重试失败，之前功能完全正常，在出错前没有任何配置以及其他插件修改。今天将版本升级到V1.3.2问题依旧存在。

PS：我是使用docker部署的，在升级最新版本时使用python:3.9.15-slim词云部分的代码会报错，改成python:3.10.11-slim后可以正常启动程序。

### Mirai 配置

```YAML
adapters:
  - http 
  - ws
debug: true
enableVerify: true
verifyKey: xxxxxx
singleMode: false
cacheSize: 4096
adapterSettings:
  http:
    host: localhost # 需要修改并匹配的对象
    port: 9090     # 需要修改并匹配的对象
    cors: [*]
  ws:
    host: localhost
    port: 9090
    reservedSyncId: -1
```

### BBot 配置

```YAML
# 警告: 在 bot 第一次成功运行后配置文件将会被规范化, 此文件中的注释均会被清除,
# 并且配置项顺序可能会出现变动, 若需要查看配置项的详细信息可参考配置文档
# https://github.com/djkcyl/BBot-Graia/wiki/fill-config

Mirai:
  mirai_host: http://localhost:9090  # **需要** 填入 mirai-api-http 的监听地址
  verify_key: xxxxxx              # **需要** 填入 mirai 的密钥
  account: 123                # **需要** 填入 bot 的 qq 号
Debug:
  enable: false      # 是否开启 debug
  groups:            # 若开启 debug 则 **需要** 填入群号, list 里填 int
    - 123456789
Bilibili:
  mobile_style: true # 是否采用手机的 Web 样式进行截图
  use_login: false   # 是否使用登录的 BiliBili 账号进行动态监听（不要开）
  username:          # BiliBili 账号，若填写则会在启动后自动登录，并且用于部分功能，如 AI 字幕
  password:          # BiliBili 密码
  concurrency: 5     # 未登录时发送 gRPC 请求的并发数量(1 ~ 50)
  dynamic_font: "HarmonyOS_Sans_SC_Medium.ttf" # 自定义动态字体
  dynamic_font_source: "local"            # 自定义动态字体来源, 可选值: "local", "remote", "system", 为 "local" 时请将字体文件放在 data/font 目录下
  openai_summarization: false             # 是否使用 OpenAI 进行视频和专栏的 AI 总结
  openai_api_token: "sk-xxxxxxxxxxxxxx"   # OpenAI API Token
  openai_model: "gpt-3.5-turbo-0301"      # OpenAI 模型
  openai_proxy: "http://localhost:7890"   # 请求 OpenAI 所用的代理
  use_wordcloud: false                     # 是否使用词云
  use_bcut_asr: false                      # 是否使用 BCut 进行 AI 语音识别
  asr_length_threshold: 60                # 调用语音识别的最小长度阈值（秒）
Event:
  mute: true         # 是否向管理员发送被禁言的事件提醒。
  permchange: true   # 是否向管理员发送权限变更的事件提醒。
  push: true         # 是否向管理员发送推送的事件提醒。
  subscribe: true    # 是否向管理员发送订阅的事件提醒。
Webui:
  webui_host: "0.0.0.0"
  webui_port: 6080
  webui_enable: true
log_level: INFO      # 控制台输出的日志等级
name: BBot           # bot 的自称
access_control: true # 是否开启白名单模式
master: 123 # **需要** 填入 bot 主人的 qq 号
admins:              # 可以填入 bot 管理员的 qq 号, list 里填 int
  - 123
max_subsubscribe: 4  # 非 vip 群聊最大可订阅数量
update_check: false   # 是否检查更新

# 警告: 在 bot 第一次成功运行后配置文件将会被规范化, 此文件中的注释均会被清除, 
# 并且配置项顺序可能会出现变动, 若需要查看配置项的详细信息可参考配置文档
# https://github.com/djkcyl/BBot-Graia/wiki/fill-config
```

### 在此处填写 Mirai 日志

```Text
none
```

### 在此处填写 BBot 日志

```Text
2023-05-29 17:56:58.729 | INFO     | aunly_bbot.utils.browser_shot:screenshot:56 - 正在截图动态：801202440850374656
2023-05-29 17:57:04.245 | ERROR    | aunly_bbot.utils.browser_shot:screenshot:73 - [BiliBili推送] 801202440850374656 动态截图失败，正在重试：
Traceback (most recent call last):

  File "/bbot/main.py", line 35, in <module>
    main()
    └ <Group main>

  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fc090fcf0a0>
           └ <Group main>
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fc09155cc10>
         │    └ <function MultiCommand.invoke at 0x7fc090fd40d0>
         └ <Group main>
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fc0912b31f0>
           │               │       │       └ <function Command.invoke at 0x7fc090fcfb50>
           │               │       └ <Command run>
           │               └ <click.core.Context object at 0x7fc0912b31f0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fc09162fd90>
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'test': False, 'skip_verfiy': False, 'ignore_sub': False}
           │   │      │    │           └ <click.core.Context object at 0x7fc0912b31f0>
           │   │      │    └ <function run_bot at 0x7fc090062c20>
           │   │      └ <Command run>
           │   └ <function Context.invoke at 0x7fc090fce8c0>
           └ <click.core.Context object at 0x7fc0912b31f0>
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'test': False, 'skip_verfiy': False, 'ignore_sub': False}
                       └ ()

  File "/bbot/aunly_bbot/cli/__init__.py", line 33, in run_bot
    run_bot()
    └ <function run_bot at 0x7fc08f17cf70>

  File "/bbot/aunly_bbot/cli/run.py", line 17, in run_bot
    app.launch_blocking()
    │   └ <classmethod(<function Ariadne.launch_blocking at 0x7fc08ec8af80>)>
    └ <graia.ariadne.app.Ariadne object at 0x7fc08f176800>

  File "/usr/local/lib/python3.10/site-packages/graia/ariadne/app.py", line 312, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x7fc08ec998f0>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x7fc08f177610>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x7fc08f02a320>
    │   └ <launart.manager.Launart object at 0x7fc08c550df0>
    └ <class 'graia.ariadne.app.Ariadne'>
  File "/usr/local/lib/python3.10/site-packages/launart/manager.py", line 494, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /usr/local/lib/python3.10/site-packages/launart/manager...
    │    └ <function BaseEventLoop.run_until_complete at 0x7fc0907052d0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7fc090705240>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7fc090706d40>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7fc0906a2710>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "/bbot/aunly_bbot/function/pusher/dynamic.py", line 368, in check_uid
    await push(app, dyn)
          │    │    └ card_type: draw
          │    │      modules {
          │    │        module_type: module_author
          │    │        module_author {
          │    │          mid: 24642415
          │    │          ptime_label_text: "2分钟前"
          │    │          a...
          │    └ <graia.ariadne.app.Ariadne object at 0x7fc08f176800>
          └ <function push at 0x7fc089751480>

  File "/bbot/aunly_bbot/function/pusher/dynamic.py", line 183, in push
    shot_image = await get_dynamic_screenshot(dyn)
                       │                      └ card_type: draw
                       │                        modules {
                       │                          module_type: module_author
                       │                          module_author {
                       │                            mid: 24642415
                       │                            ptime_label_text: "2分钟前"
                       │                            a...
                       └ <function get_dynamic_screenshot at 0x7fc0896e15a0>

  File "/bbot/aunly_bbot/utils/dynamic_shot.py", line 12, in get_dynamic_screenshot
    return await browser_dynamic(dyn.extend.dyn_id_str)
                 │               └ card_type: draw
                 │                 modules {
                 │                   module_type: module_author
                 │                   module_author {
                 │                     mid: 24642415
                 │                     ptime_label_text: "2分钟前"
                 │                     a...
                 └ <function browser_dynamic at 0x7fc0889cde10>

  File "/bbot/aunly_bbot/utils/browser_shot.py", line 52, in browser_dynamic
    return await screenshot(dynid, browser_context)
                 │          │      └ <BrowserContext browser=None>
                 │          └ '801202440850374656'
                 └ <function screenshot at 0x7fc0889cd990>

> File "/bbot/aunly_bbot/utils/browser_shot.py", line 66, in screenshot
    page, clip = await get_mobile_screenshot(page, dynid)
    │                  │                     │     └ '801202440850374656'
    │                  │                     └ <Page url='https://m.bilibili.com/dynamic/801202440850374656'>
    │                  └ <function get_mobile_screenshot at 0x7fc0889cdd80>
    └ <Page url='https://m.bilibili.com/dynamic/801202440850374656'>

  File "/bbot/aunly_bbot/utils/browser_shot.py", line 147, in get_mobile_screenshot
    assert card
           └ None

AssertionError: assert card
```
